import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./Pages/navigation/Navbar";
import Footer from "./Pages/navigation/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-zinc-50 font-sans dark:bg-black">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
